services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=docs
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d docs" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - deploy_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python -m alembic upgrade head && python main.py"
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - deploy_network

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 5981:5981
    depends_on:
      - api
    networks:
      - deploy_network


volumes:
  pgdata:

networks:
  deploy_network:
    driver: bridge